### ISSUE TITLE
changing file when markers are in place causes incorrect jumping.

### ISSUE THREAD

**Issue by jordwalke** [AtomLinter/linter-ui-default#47] opened 2016-03-15 07:42 UTC
Here's the repro:

- Disable "on the fly" checking.
- Make there be red underlines. Verify that clicking on the summary at the bottom of screen jumps to correct location.
- Without saving the file, add newlines above the errors pushing the red lines downward. The redlines correctly follow the text.
- But when clicking on the lower panel error, it jumps to the old location. I believe they should track the text as it's being edited.

**Comment by steelbrain** [comment] 2016-03-15 07:44
I think this is working as intended, the editor does not know the accurate position after you edit text. Getting the new position from the provider are the only way to fix this.

As a workaround you could also close/re-open the tab

**Comment by steelbrain** [comment] 2016-03-15 07:45
Oh wait, do you mean that the text that is not the error is highlighted? In that case, yes it is a bug. We could update the message object with the latest marker positions we get so message registry can invalidate it and send the UI provider a more accurate message

**Comment by jordwalke** [comment] 2016-03-15 07:51
I'll clarify. The text that is highlighted is the actual error. When I insert newlines into the document, the red text tracks correctly with the original text that was highlighted red. Imagine the red underlines being "sticky" on the problematic original text. That part is correct. What is *incorrect* is that jumping to "next error" or clicking on the bottom panel to go to the error, now does *not* go to the red underline location. It goes to the range that *originally* had the red underline before you inserted a bunch of newlines. Something somewhere knows where those red underlines are - because the document shows them as being moved.

**Comment by steelbrain** [comment] 2016-03-15 07:59
Oh okay, to overcome this issue we'll have to not only keep the message pointers up to date of the changes but also re-render the panel everytime editor text changes. These recalculations are pretty cpu time costly in master, but in #40 they should be good

Thank you again for bringing this up to our attention

**Comment by steelbrain** [comment] 2016-03-18 09:48
This has been fixed in https://github.com/AtomLinter/linter-ui-default/issues/40

**Closed** 2016-03-18 09:53 UTC
Labels: bug
